### ISSUE TITLE
Problems with the display of apps

### ISSUE THREAD

**Issue by linux-lukas** [ccmjs/digital-makerspace#1]
No apps are displayed to me.

**Comment by akless** [comment]
If you go to "Apps" at the web address "https://ccmjs.github.io/digital-makerspace/", you should get a list of all apps that others have already created in Digital Makerspace. The top entry should be an English fill-in-the-blank text with the title "Active vs Passive Voice". At which point exactly do you see no apps?

**Comment by linux-lukas** [comment]
Okay, the problem seems to be solved. The integrated page of the Bonn University of Applied Sciences was not displayed at first without noscript and umatrix. That was the problem. 

I'm sorry for the inconvenience.
